### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe0' in file char_dictionary.py

### ISSUE THREAD

**Issue by kobkrit** [pucktada/cutkum#1]
Mac OS X Sierra 10.12.4
Python 2.7.11

----
kv:cutkum kobkrit$ python cutkum.py -m model/ck.r8.s128.l3.meta -c model/ck.r8.s128.l3 -s "สารานุกรมไทยสำหรับเยาวชนฯ"
Traceback (most recent call last):
  File "cutkum.py", line 17, in <module>
    from char_dictionary import CharDictionary
  File "/Users/kobkrit/git/cutkum/char_dictionary.py", line 15
SyntaxError: Non-ASCII character '\xe0' in file /Users/kobkrit/git/cutkum/char_dictionary.py on line 15, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
kv:cutkum kobkrit$

**Comment by kobkrit** [comment]
I have seen requirement of python >=3.0. Close.

**Comment by pucktada** [comment]
^___^ yes, require python >= 3.0

The only reason I use Python 3.0 because it's easier to deal with Unicode in 3.0 than in 2.7, but in the new update I will make it compatible with both 2.7 and 3.0 (I actually already made the change, so in the next push, it should work with both 3.0 and 2.7
