### ISSUE TITLE
CharDictionary

### ISSUE THREAD

**Issue by praphan-amv** [pucktada/cutkum#2]
ขอบคุณที่ contribute และ opensource โปรเจคนี้นะครับ

ผมมาพร้อมกับคำถามว่าทำไม char dictionay มันเริ่มที่ 2 ครับ
```
testing character dictionary
['ก', 'ฎ', 'ห', 'ม', 'า', 'ย', 'ก', 'ั', 'บ', '1', 'ก', 'า', 'ร', 'เ', 'บ', 'ี', 'ย', 'ด', 'บ', 'ั', 'ง', 'ค', 'น']
[2, 16, 45, 35, 52, 36, 2, 51, 28, 74, 2, 52, 37, 60, 28, 55, 36, 22, 28, 51, 8, 5, 27
```

**Comment by pucktada** [comment]
ยินดีครับ :) char dictionary จริงๆ เริ่มที่ 0 ครับ แต่ผมเก็บ '0' ไว้สำหรับ padding และ '1' ไว้สำหรับ UNKNOWN character ที่ไม่ใช่ ภาษาไทย หรือ a-zA-Z หรือตัวเลขครับ ดังนั้น 'ก' เลยเริ่มที่ 2 ครับ

ขอปิด issue นะครับ
