### ISSUE TITLE
รบกวนสอบถามข้อมูลเพิ่มเติมค่ะ

### ISSUE THREAD

**Issue by nampornpimon** [pucktada/cutkum#3]
เรียนคุณ Puck ค่ะ
ได้ลองทำตามข้อมูลที่คุณ Puck เขียนไว้ ซึ่งตอนนี้มีปัญหาที่ขอสอบถามข้อมูลเพิ่มเติมดังนี้ค่ะ
1. มี Code ที่สามารถใช้กับ python 3 (Version 3.6.2) เพื่อให้สามารถใช้งานได้กับระบบ Windows หรือไม่คะ
2. เนื่องจากไม่สามารถ Export ออกมา Save File ได้ จึงจะรบกวนสอบถามเพิ่มเติมว่ามีวิธี หรือมี Coding อะไรที่จะ Export ออกมา Save File เป็น .txt ได้ไหมคะ
ขอบคุณค่ะ

**Comment by pucktada** [comment]
1. เพิ่งแก้ code ให้ใช้ได้กับทั้ง python 3 และ python 2.7 ครับ
2. เพิ่ม method ทำให้สามารถให้ตัดคำของทุก file ใน directory หนึ่ง แล้ว save ผลลงในอีก directory หนึ่งครับ 

เผอิญยุ่งๆมากเมื่อสิ้นปี :) อาจจะไม่ทันสำหรับคุณ nampornpimon  แต่หวังว่าอาจจะมีประโยชน์ สำหรับคนอื่นครับ

**Comment by nampornpimon** [comment]
ขอบคุณมากเลยค่ะ ^^
