### ISSUE TITLE
RuntimeError when using numpy 1.13.0. Fixed with numpy 1.14.0

### ISSUE THREAD

**Issue by bact** [pucktada/cutkum#4]
After cutkum installation using pip (pip install cutkum),
importing cutkum (from cutkum.tokenizer import Cutkum) yields this error message:

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

The system uses numpy 1.13.0 and tensorflow 1.5.0.

After change numpy version to 1.14.0, the error disappear.

**Comment by pucktada** [comment]
Thank You for the Fix... :) i changed it to lower the requirement a bit to tensorflow 1.4.0 for now..

**Comment by bact** [comment]
Thanks, agree with that.
It looks like we just need a right pair of numpy and tensorflow versions.
